/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class AplikasiPertambahanAngka extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPertambahanAngka
     */
    public AplikasiPertambahanAngka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        hapus = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        nilai1 = new javax.swing.JTextField();
        nilai2 = new javax.swing.JTextField();
        nilaiHasil = new javax.swing.JTextField();
        angka1 = new javax.swing.JLabel();
        angka2 = new javax.swing.JLabel();
        hasil = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplikasi Pertambahan Angka", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PMingLiU-ExtB", 1, 14))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 5, 14);
        jPanel1.add(hapus, gridBagConstraints);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 0);
        jPanel1.add(tambah, gridBagConstraints);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(21, 14, 5, 3);
        jPanel1.add(keluar, gridBagConstraints);

        nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilai1ActionPerformed(evt);
            }
        });
        nilai1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nilai1KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 0);
        jPanel1.add(nilai1, gridBagConstraints);

        nilai2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nilai2KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 0);
        jPanel1.add(nilai2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 0);
        jPanel1.add(nilaiHasil, gridBagConstraints);

        angka1.setText("Masukkan Angka Pertama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(angka1, gridBagConstraints);

        angka2.setText("Masukkan Angka Kedua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(angka2, gridBagConstraints);

        hasil.setText("Lihat Hasil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(hasil, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // Menutup aplikasi
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // Mengambil nilai dari text field nilai1 dan nilai2
        String textNilai1 = nilai1.getText();
        String textNilai2 = nilai2.getText();

        // Validasi input apakah berupa angka
        try {
            int angka1 = Integer.parseInt(textNilai1);
            int angka2 = Integer.parseInt(textNilai2);

            // Melakukan penambahan dua angka
            int hasil = angka1 + angka2;

            // Menampilkan hasil penambahan pada text field nilaiHasil
            nilaiHasil.setText(String.valueOf(hasil));
        } catch (NumberFormatException e) {
            // Menampilkan pesan error jika input bukan angka
            nilaiHasil.setText("Input tidak valid");
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilai1ActionPerformed
    // Memindahkan fokus ke text field nilai2
    nilai2.requestFocus();
}//GEN-LAST:event_nilai1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    // Mengosongkan semua text field
        nilai1.setText("");
        nilai2.setText("");
        nilaiHasil.setText("");
        // Memindahkan fokus ke text field nilai1
        nilai1.requestFocus();
    }//GEN-LAST:event_hapusActionPerformed

    private void nilai1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai1KeyTyped
    char c = evt.getKeyChar();
    if (!Character.isDigit(c) && c != '\b' && c != '\n') {
        evt.consume();  // Mengabaikan karakter non-digit kecuali backspace dan enter
        javax.swing.JOptionPane.showMessageDialog(this, "Input harus berupa angka", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_nilai1KeyTyped

    private void nilai2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai2KeyTyped
    char c = evt.getKeyChar();
    if (!Character.isDigit(c) && c != '\b' && c != '\n') {
        evt.consume();  // Mengabaikan karakter non-digit kecuali backspace dan enter
        javax.swing.JOptionPane.showMessageDialog(this, "Input harus berupa angka", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_nilai2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPertambahanAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPertambahanAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPertambahanAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPertambahanAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPertambahanAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angka1;
    private javax.swing.JLabel angka2;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel hasil;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nilai1;
    private javax.swing.JTextField nilai2;
    private javax.swing.JTextField nilaiHasil;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
